#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="$HOME"
OUTPUTDIR="$HOME/output"
ROOTFS="archlinux-bootstrap-x86_64.tar.gz"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then
        sudo wget https://mirror.alwyzon.net/archlinux/iso/2024.04.01/$ROOTFS
    fi
    if [ -d root.x86_64 ]; then sudo rm -r root.x86_64; fi
    sudo bsdtar -xf $ROOTFS
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR 
    sudo mkdir -p root.x86_64/proc/self/
    sudo cp -af /proc/self/mounts root.x86_64/proc/self/mounts
    sudo mkdir -p root.x86_64/dev/fd/; touch root.x86_64/dev/fd/63
    sudo cp /etc/resolv.conf root.x86_64/etc/
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e 'Server=https://mirror.alwyzon.net/archlinux/\$repo/os/\$arch'>/etc/pacman.d/mirrorlist"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e '[aurci2]\nSigLevel = Optional TrustAll\nServer = https://github.com/simargl/aurci2/releases/download/aurci2' >> /etc/pacman.conf"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman-key --init"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman-key --populate archlinux"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -Syu --noconfirm"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -S transmission-gtk \
    vte3 gtksourceview3 nss wget libice libsm libxss libxpresent \
    libxv alsa-utils zathura-pdf-poppler git imv desktop-file-utils mesa \
    dbus-glib librsvg syslinux xorriso cpio unrar unzip net-tools htop \
    xorg-mkfontscale ntfs-3g python-gobject webp-pixbuf-loader xdg-utils \
    lshw labwc seatd xorg-xwayland swaybg waybar ttf-font-awesome gammastep \
    libnotify fuse2 geany pcre mako android-tools grim mpv openh264 yt-dlp \
    mpg123 dhcpcd rsync fltk base-devel sdl2_image expac less inetutils --noconfirm"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "rm /var/cache/pacman/pkg/*"
    # cache
    sudo rm -r $STARTDIR/root.x86_64/usr/share/mime/globs
    sudo rm -r $STARTDIR/root.x86_64/usr/share/icons/hicolor/icon-theme.cache
    sudo rm -r $STARTDIR/root.x86_64/usr/share/glib-2.0/schemas/gschemas.compiled
    # other
    sudo rm -r $STARTDIR/root.x86_64/usr/lib/locale
    sudo rm -r $STARTDIR/root.x86_64/usr/share/doc
    sudo rm -r $STARTDIR/root.x86_64/usr/share/info
    sudo rm -r $STARTDIR/root.x86_64/usr/share/licenses
    sudo rm -r $STARTDIR/root.x86_64/usr/share/locale
    sudo rm -r $STARTDIR/root.x86_64/usr/share/man
    sudo rm -r $STARTDIR/root.x86_64/pkglist.x86_64.txt
    sudo rm -r $STARTDIR/root.x86_64/version
    find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | sudo xargs rm
    find $STARTDIR/root.x86_64/ -type f -name '*.log' | sudo xargs rm
    # compress
    if [ ! -d $OUTPUTDIR ]; then sudo mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-arch.sb ]; then sudo rm $OUTPUTDIR/fs-arch.sb; fi
    sudo mksquashfs root.x86_64/ $OUTPUTDIR/fs-arch.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_and_compress
