#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="/tmp"
OUTPUTDIR="/tmp/output"
ROOTFS="archlinux-bootstrap-x86_64.tar.zst"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then
        wget https://mirror.alwyzon.net/archlinux/iso/2025.01.01/$ROOTFS
    fi
    if [ -d root.x86_64 ]; then rm -r root.x86_64; fi
    bsdtar -xf $ROOTFS
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR 
    mkdir -p root.x86_64/proc/self/
    cp -af /proc/self/mounts root.x86_64/proc/self/mounts
    mkdir -p root.x86_64/dev/fd/; touch root.x86_64/dev/fd/63
    cp /etc/resolv.conf root.x86_64/etc/
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e 'Server=https://mirror.alwyzon.net/archlinux/\$repo/os/\$arch'>/etc/pacman.d/mirrorlist"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman-key --init"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman-key --populate archlinux"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -Syu --noconfirm"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -S transmission-gtk \
    vte3 gtksourceview3 nss wget libice libsm libxss libxpresent \
    libxv alsa-utils zathura-pdf-poppler git desktop-file-utils mesa \
    dbus-glib librsvg syslinux xorriso cpio unrar unzip net-tools htop \
    xorg-mkfontscale ntfs-3g python-gobject webp-pixbuf-loader xdg-utils \
    lshw openbox zathura-pdf-poppler redshift tint2 dunst conky feh gmrun \
    lxappearance-gtk3 obconf xorg-server xorg-xinit xcompmgr ttf-font-awesome \
    libnotify fuse2 geany pcre android-tools mpv openh264 yt-dlp libxslt \
    mpg123 dhcpcd rsync base-devel sdl2_image expac less inetutils nemo \
    nemo-fileroller --noconfirm"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "rm /var/cache/pacman/pkg/*"
    sed -i 's/geteuid/getppid/' $STARTDIR/root.x86_64/usr/bin/nemo
    # cache
    rm -r $STARTDIR/root.x86_64/usr/share/mime/globs
    rm -r $STARTDIR/root.x86_64/usr/share/icons/hicolor/icon-theme.cache
    rm -r $STARTDIR/root.x86_64/usr/share/glib-2.0/schemas/gschemas.compiled
    # other
    rm -r $STARTDIR/root.x86_64/usr/share/doc
    rm -r $STARTDIR/root.x86_64/usr/share/info
    rm -r $STARTDIR/root.x86_64/usr/share/licenses
    rm -r $STARTDIR/root.x86_64/usr/share/locale
    rm -r $STARTDIR/root.x86_64/usr/share/man
    find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | xargs rm
    find $STARTDIR/root.x86_64/ -type f -name '*.log' | xargs rm
    # compress
    if [ ! -d $OUTPUTDIR ]; then mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-arch.sb ]; then rm $OUTPUTDIR/fs-arch.sb; fi
    mksquashfs root.x86_64/ $OUTPUTDIR/fs-arch.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_and_compress
