#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="/tmp"
OUTPUTDIR="/mnt/home/data/Downloads"
SETS=("core" "graphics" "ui")
STAGE="stage0"
VERSION="a5"

fn_download_and_extract() {
    cd $STARTDIR
    if [ -d root.x86_64 ]; then sudo rm -r root.x86_64; fi
    sudo mkdir root.x86_64
    for S in ${SETS[@]}; do
        if [ ! -f rootfs-slik-linux-$STAGE-$S-$VERSION.tar.xz ]; then
            sudo wget https://github.com/simargl/slik-linux-jolt/releases/download/$STAGE-$VERSION/rootfs-slik-linux-$STAGE-$S-$VERSION.tar.xz -q --show-progress
        fi
        sudo tar -xf rootfs-slik-linux-$STAGE-$S-$VERSION.tar.xz -C root.x86_64
    done
    sudo mv root.x86_64/root.spkg/* root.x86_64; rmdir root.x86_64/root.spkg
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR
    sudo cp /etc/resolv.conf root.x86_64/etc/
    # cache
    sudo rm -r $STARTDIR/root.x86_64/usr/share/mime/globs*
    # other
    if [ -d $STARTDIR/root.x86_64/usr/share/doc ]; then sudo rm -r $STARTDIR/root.x86_64/usr/share/doc; fi
    if [ -d $STARTDIR/root.x86_64/usr/share/info ]; then sudo rm -r $STARTDIR/root.x86_64/usr/share/info; fi
    if [ -d $STARTDIR/root.x86_64/usr/share/licenses ]; then sudo rm -r $STARTDIR/root.x86_64/usr/share/licenses; fi
    if [ -d $STARTDIR/root.x86_64/usr/share/locale ]; then sudo rm -r $STARTDIR/root.x86_64/usr/share/locale; fi
    if [ -d $STARTDIR/root.x86_64/usr/share/man ]; then sudo rm -r $STARTDIR/root.x86_64/usr/share/man; fi
    find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | xargs sudo rm
    # compress
    if [ ! -d $OUTPUTDIR ]; then sudo mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-slik.sb ]; then sudo rm $OUTPUTDIR/fs-slik.sb; fi
    sudo mksquashfs root.x86_64/ $OUTPUTDIR/fs-slik.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_and_compress
