#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="/tmp"
OUTPUTDIR="/tmp/output"
ROOTFS="ubuntu-base-18.04.5-base-amd64.tar.gz"
VERSION=$(echo "$ROOTFS" | awk -F'-' '{print $3}')     #18.04.5 22.04.5 26.04

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then wget https://cdimage.ubuntu.com/ubuntu-base/releases/$VERSION/release/$ROOTFS; fi
    if [ -d root.x86_64 ]; then rm -r root.x86_64; fi
    mkdir root.x86_64
    tar -xf $ROOTFS -C root.x86_64
    if [ ! -f yt-dlp ]; then wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -O yt-dlp; fi
}

fn_build_rootfs() {
    # prepare
    cd $STARTDIR
    cp /etc/resolv.conf root.x86_64/etc/
    if [ -f root.x86_64/etc/mtab ]; then rm root.x86_64/etc/mtab; fi
    if [ -f root.x86_64/dev/null ]; then rm root.x86_64/dev/null; fi   
    cp -af /proc/self/mounts root.x86_64/etc/mtab
    mknod -m 0666 root.x86_64/dev/null c 1 3
    mknod -m 0666 root.x86_64/dev/random c 1 8
    mknod -m 0666 root.x86_64/dev/urandom c 1 9
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "mount -t proc /proc /proc"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "mount -t sysfs /sys /sys"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "apt update -y && apt upgrade -y"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e 'APT::Install-Recommends \"0\";\nAPT::Install-Suggests \"0\";' > \
    /etc/apt/apt.conf.d/999norecommend"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install \
    transmission-gtk libvte-2.91-0 libgtksourceview-3.0-1 libnss3 wget libxss1 \
    alsa-utils zathura git desktop-file-utils psmisc libpangoxft-1.0-0 \
    libnotify-bin net-tools isc-dhcp-client adwaita-icon-theme xorriso syslinux \
    cpio libglib2.0-bin libfuse2 ntfs-3g htop librsvg2-bin libdbus-glib-1-2 \
    unrar conky-std unzip file apt-utils tzdata libxv1 dbus-x11 dbus librsvg2-common \
    lshw less python3-gi gir1.2-gtk-3.0 python3-cairo libvorbisfile3 redshift \
    dunst feh gmrun lxappearance obconf openbox scrot xinit xserver-xorg \
    libharfbuzz-gobject0 udev ca-certificates pulseaudio xz-utils curl whiptail \
    rsync bzip2 mpv dhcpcd5 build-essential libsdl2-image-2.0-0 gsettings-desktop-schemas \
    xfonts-utils mpg123 libxslt1.1 at-spi2-core x11-xserver-utils lm-sensors \
    software-properties-common pciutils gvfs libgles2 libgtk-3-dev pkg-config \
    gir1.2-gtksource-3.0 python3-tk eject ffmpeg rofi adb xdotool wmctrl \
    zstd libglu1-mesa usbutils fonts-dejavu-core pysassc nano compton libgl1-mesa-dev \
    meson libvte-2.91-dev bsdtar -y"
    if [[ $VERSION != *18.04* ]]; then
        chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install picom libgtk-4-dev -y"
    fi    
    if [[ $VERSION == *18.04* || $VERSION == *22.04* ]]; then
        chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install gnome-icon-theme \
        gtk2-engines-murrine gtk2-engines-pixbuf libgtkglext1 libpangox-1.0-0 -y"
    fi    
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "apt clean; dpkg --configure -a; apt-get install -f"
    install -m755 yt-dlp $STARTDIR/root.x86_64/usr/bin/yt-dlp
    ln -sf yt-dlp $STARTDIR/root.x86_64/usr/bin/youtube-dl
    ln -sf bash $STARTDIR/root.x86_64/bin/sh
    ln -sf python3 $STARTDIR/root.x86_64/usr/bin/python
    # cache
    rm -r $STARTDIR/root.x86_64/usr/share/{applications/mimeinfo.cache,mime/globs,icons/hicolor/icon-theme.cache,icons/Adwaita/icon-theme.cache,glib-2.0/schemas/gschemas.compiled}
    # other
    rm -r $STARTDIR/root.x86_64/usr/share/{doc,info,locale,man}
    find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | xargs rm
    find $STARTDIR/root.x86_64/usr/share/icons/ -mindepth 1 -maxdepth 1 -type d ! \( -name hicolor -o -name Adwaita -o -name default -o -name gnome \) -exec rm -r {} +
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "umount /proc"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "umount /sys"
}

fn_compress_rootfs() {
    cd $STARTDIR
    if [ ! -d $OUTPUTDIR ]; then mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-ubuntu.sb ]; then rm $OUTPUTDIR/fs-ubuntu.sb; fi
    mksquashfs root.x86_64/ $OUTPUTDIR/fs-ubuntu.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_rootfs
fn_compress_rootfs
