#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="$HOME"
OUTPUTDIR="$HOME/output"
ROOTFS="ubuntu-noble-oci-amd64-root.tar.gz"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then wget "https://git.launchpad.net/cloud-images/+oci/ubuntu-base/plain/ubuntu-noble-oci-amd64-root.tar.gz?h=noble-24.04" -O $ROOTFS; fi
    if [ -d root.x86_64 ]; then sudo rm -r root.x86_64; fi
    sudo mkdir root.x86_64
    sudo tar -xf $ROOTFS -C root.x86_64
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR
    sudo cp /etc/resolv.conf root.x86_64/etc/
    if [ -f root.x86_64/etc/mtab ]; then sudo rm root.x86_64/etc/mtab; fi
    if [ -f root.x86_64/dev/null ]; then sudo rm root.x86_64/dev/null; fi   
    sudo cp -af /proc/self/mounts root.x86_64/etc/mtab
    sudo mknod -m 666 root.x86_64/dev/null c 1 3
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "apt update -y && apt upgrade -y"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e 'APT::Install-Recommends \"0\";\nAPT::Install-Suggests \"0\";' > \
    /etc/apt/apt.conf.d/999norecommend"
    sudo chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install \
    transmission-gtk libvte-2.91-0 libgtksourceview-3.0-1 swayimg libnss3 \
    wget libxss1 alsa-utils zathura-pdf-poppler git desktop-file-utils psmisc \
    libpangoxft-1.0-0 libarchive-tools libnotify-bin net-tools isc-dhcp-client \
    adwaita-icon-theme xorriso syslinux cpio libglib2.0-bin libfuse2 \
    libopengl0 ntfs-3g htop libxpresent1 librsvg2-bin libdbus-glib-1-2 unrar \
    unzip file apt-utils tzdata libxv1 dbus-user-session dbus librsvg2-common \
    lshw less python3-gi gir1.2-gtk-3.0 python3-cairo webp-pixbuf-loader \
    labwc xwayland geany waybar swaybg gammastep fonts-font-awesome \
    libharfbuzz-gobject0 udev ca-certificates mako-notifier yt-dlp \
    xz-utils adb grim curl whiptail rsync bzip2 mpv mpg123 dhcpcd-base \
    libfltk1.3-dev build-essential libsdl2-image-2.0-0 gsettings-desktop-schemas \
    seatd xfonts-utils -y"
    sudo ln -sf bash $STARTDIR/root.x86_64/usr/bin/sh
    # cache
    sudo rm -r $STARTDIR/root.x86_64/usr/share/{applications/mimeinfo.cache,mime/globs,icons/hicolor/icon-theme.cache,glib-2.0/schemas/gschemas.compiled}
    # other
    sudo rm -r $STARTDIR/root.x86_64/{bin.usr-is-merged,lib.usr-is-merged,sbin.usr-is-merged}
    sudo rm -r $STARTDIR/root.x86_64/usr/lib/locale
    sudo rm -r $STARTDIR/root.x86_64/usr/share/{doc,info,locale,man}
    sudo rm -r $STARTDIR/root.x86_64/usr/share/icons/{Humanity,Humanity-Dark,ubuntu-mono-dark,ubuntu-mono-light}
    sudo find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | sudo xargs rm
    # compress
    if [ ! -d $OUTPUTDIR ]; then sudo mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-ubuntu.sb ]; then sudo rm $OUTPUTDIR/fs-ubuntu.sb; fi
    sudo mksquashfs root.x86_64/ $OUTPUTDIR/fs-ubuntu.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_and_compress
