#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

STARTDIR="/tmp"
OUTPUTDIR="/tmp/output"
ROOTFS="oracular-base-amd64.tar.gz"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then wget https://cdimage.ubuntu.com/ubuntu-base/daily/current/$ROOTFS; fi
    if [ -d root.x86_64 ]; then rm -r root.x86_64; fi
    mkdir root.x86_64
    tar -xf $ROOTFS -C root.x86_64
}

fn_build_rootfs() {
    # prepare
    cd $STARTDIR
    cp /etc/resolv.conf root.x86_64/etc/
    if [ -f root.x86_64/etc/mtab ]; then rm root.x86_64/etc/mtab; fi
    if [ -f root.x86_64/dev/null ]; then rm root.x86_64/dev/null; fi   
    cp -af /proc/self/mounts root.x86_64/etc/mtab
    mknod -m 666 root.x86_64/dev/null c 1 3
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "apt update -y && apt upgrade -y"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "echo -e 'APT::Install-Recommends \"0\";\nAPT::Install-Suggests \"0\";' > \
    /etc/apt/apt.conf.d/999norecommend"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install \
    transmission-gtk libvte-2.91-0 libgtksourceview-3.0-1 swayimg libnss3 \
    wget libxss1 alsa-utils zathura-pdf-poppler git desktop-file-utils psmisc \
    libpangoxft-1.0-0 libarchive-tools libnotify-bin net-tools isc-dhcp-client \
    adwaita-icon-theme xorriso syslinux cpio libglib2.0-bin libfuse2 \
    libopengl0 ntfs-3g htop libxpresent1 librsvg2-bin libdbus-glib-1-2 unrar \
    unzip file apt-utils tzdata libxv1 dbus-user-session dbus librsvg2-common \
    lshw less python3-gi gir1.2-gtk-3.0 python3-cairo webp-pixbuf-loader \
    labwc xwayland geany waybar swaybg gammastep fonts-font-awesome \
    libharfbuzz-gobject0 udev ca-certificates mako-notifier yt-dlp \
    xz-utils adb grim curl whiptail rsync bzip2 mpv dhcpcd-base \
    libfltk1.3-dev build-essential libsdl2-image-2.0-0 gsettings-desktop-schemas \
    seatd xfonts-utils mpg123 -y"
    ln -sf bash $STARTDIR/root.x86_64/usr/bin/sh
    # cache
    rm -r $STARTDIR/root.x86_64/usr/share/{applications/mimeinfo.cache,mime/globs,icons/hicolor/icon-theme.cache,glib-2.0/schemas/gschemas.compiled}
    # other
    rm -r $STARTDIR/root.x86_64/usr/lib/locale
    rm -r $STARTDIR/root.x86_64/usr/share/{doc,info,locale,man}
    rm -r $STARTDIR/root.x86_64/usr/share/icons/{Humanity,Humanity-Dark,ubuntu-mono-dark,ubuntu-mono-light}
    find $STARTDIR/root.x86_64/usr/share/applications -type f -not -name transmission-gtk.desktop | xargs rm
}

fn_compress_rootfs() {
    cd $STARTDIR
    if [ ! -d $OUTPUTDIR ]; then mkdir -p $OUTPUTDIR; fi
    if [ -f $OUTPUTDIR/fs-ubuntu.sb ]; then rm $OUTPUTDIR/fs-ubuntu.sb; fi
    mksquashfs root.x86_64/ $OUTPUTDIR/fs-ubuntu.sb -comp gzip -b 1024k
}

fn_download_and_extract
fn_build_rootfs
fn_compress_rootfs
