#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

VERSION="0.0.1"

STARTDIR="/tmp"
OUTPUTDIR="/mnt/home/data/Downloads"
DATE="$(date +%Y.%m.01)"

ROOTFS="archlinux-bootstrap-$DATE-x86_64.tar.gz"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then
        wget http://mirror.digitalnova.at/archlinux/iso/$DATE/$ROOTFS
    fi
    tar -xf $ROOTFS
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR
    sed 's|#Server = http://mirror.digitalnova.at/archlinux/$repo/os/$arch|Server = http://mirror.digitalnova.at/archlinux/$repo/os/$arch|g' -i root.x86_64/etc/pacman.d/mirrorlist
    sed 's|SigLevel    = Required DatabaseOptional|SigLevel    = Never|g' -i root.x86_64/etc/pacman.conf
    cp /etc/resolv.conf root.x86_64/etc/
    rm root.x86_64/etc/mtab; cp -af /proc/self/mounts root.x86_64/etc/mtab
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -Syu --noconfirm"
    rm root.x86_64/etc/mtab; cp -af /proc/self/mounts root.x86_64/etc/mtab
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "pacman -S transmission-gtk lxterminal gtksourceview3 \
    base-devel xorg-server xorg-xinit feh nss wget libxss alsa-utils zathura-pdf-poppler \
    git ntfs-3g libnotify cpio redshift xorg-xset xorg-mkfontscale net-tools dhclient --needed --noconfirm"
    # cache
    rm -r $STARTDIR/root.x86_64/usr/share/applications/mimeinfo.cache
    rm -r $STARTDIR/root.x86_64/usr/share/mime/globs
    rm -r $STARTDIR/root.x86_64/usr/share/icons/hicolor/icon-theme.cache
    rm -r $STARTDIR/root.x86_64/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -r $STARTDIR/root.x86_64/var/cache/pacman/pkg/*
    # other
    rm -r $STARTDIR/root.x86_64/usr/lib/locale
    rm -r $STARTDIR/root.x86_64/usr/share/doc
    rm -r $STARTDIR/root.x86_64/usr/share/gtk-doc
    rm -r $STARTDIR/root.x86_64/usr/share/info
    rm -r $STARTDIR/root.x86_64/usr/share/licenses
    rm -r $STARTDIR/root.x86_64/usr/share/locale
    rm -r $STARTDIR/root.x86_64/usr/share/man
    find $STARTDIR/root.x86_64/usr/lib/dri -type f -not -name i965* -not -name swrast_dri* -not -name crocus_dri* -not -name iris_dri* | xargs rm
    rm $STARTDIR/root.x86_64/usr/share/applications/avahi-discover.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/bssh.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/bvnc.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/feh.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/org.pwmt.zathura-pdf-poppler.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/org.pwmt.zathura.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/lxterminal.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/redshift-gtk.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/redshift.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/geoclue-demo-agent.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/geoclue-where-am-i.desktop
    rm $STARTDIR/root.x86_64/usr/lib/libgo.so*
    # compress
    if [ ! -d $OUTPUTDIR ]; then mkdir -p $OUTPUTDIR; fi
    mksquashfs root.x86_64/ $OUTPUTDIR/fs-arch.sb
}

fn_download_and_extract
fn_build_and_compress
