#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

VERSION="0.0.1"

STARTDIR="/tmp"
OUTPUTDIR="/mnt/home/data/Downloads"
ROOTFS="rootfs.tar.xz"

fn_download_and_extract() {
    cd $STARTDIR
    if [ ! -f $ROOTFS ]; then
        wget https://github.com/debuerreotype/docker-debian-artifacts/raw/05137cb2f4d78bb95802630db60c77385dc3ae96/bookworm/$ROOTFS
    fi
    if [ ! -d root.x86_64 ]; then
        mkdir root.x86_64
    fi
    bsdtar -xf $ROOTFS -C root.x86_64
}

fn_build_and_compress() {
    # prepare
    cd $STARTDIR
    cp /etc/resolv.conf root.x86_64/etc/
    rm root.x86_64/etc/mtab; cp -af /proc/self/mounts root.x86_64/etc/mtab
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "apt update -y && apt upgrade -y"
    chroot $STARTDIR/root.x86_64/ /bin/bash -c "export DEBIAN_FRONTEND=noninteractive && apt install \
    transmission-gtk lxterminal libgtksourceview-3.0-1 xserver-xorg xinit feh libnss3 \
    wget libxss1 alsa-utils zathura-pdf-poppler git x11-xkb-utils desktop-file-utils libgl1-mesa-dri psmisc \
    x11-xserver-utils dbus-x11 libpangoxft-1.0-0 libarchive-tools build-essential redshift libnotify-bin \
    net-tools isc-dhcp-client -y"
    ln -sf bash $STARTDIR/root.x86_64/usr/bin/sh
    # cache
    rm -r $STARTDIR/root.x86_64/usr/share/applications/mimeinfo.cache
    rm -r $STARTDIR/root.x86_64/usr/share/mime/globs
    rm -r $STARTDIR/root.x86_64/usr/share/icons/hicolor/icon-theme.cache
    rm -r $STARTDIR/root.x86_64/usr/share/glib-2.0/schemas/gschemas.compiled
    # other
    rm -r $STARTDIR/root.x86_64/usr/lib/locale
    rm -r $STARTDIR/root.x86_64/usr/share/doc
    rm -r $STARTDIR/root.x86_64/usr/share/info
    rm -r $STARTDIR/root.x86_64/usr/share/locale
    rm -r $STARTDIR/root.x86_64/usr/share/man
    find $STARTDIR/root.x86_64/usr/lib/x86_64-linux-gnu/dri -type f -not -name i965* -not -name swrast_dri* -not -name crocus_dri* -not -name iris_dri* | xargs rm
    rm $STARTDIR/root.x86_64/usr/share/applications/feh.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/org.pwmt.zathura-pdf-poppler.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/org.pwmt.zathura.desktop
    rm $STARTDIR/root.x86_64/usr/share/applications/lxterminal.desktop
    # compress
    if [ ! -d $OUTPUTDIR ]; then mkdir -p $OUTPUTDIR; fi
    mksquashfs root.x86_64/ $OUTPUTDIR/fs-debian.sb
}

fn_download_and_extract
fn_build_and_compress
