#!/bin/bash
# 
# Author: simargl <https://github.com/simargl>
# License: GPL v3

# Define colors and variables

VERSION="14.2"
MAIN_MIRROR="https://mirror.de.leaseweb.net/slackware/slackware64-$VERSION"
OTHER_MIRRORS=( "https://repo.greeklug.gr/data/pub/linux/salix/x86_64/$VERSION"
                "https://repo.greeklug.gr/data/pub/linux/salix/x86_64/extra-$VERSION")

DBPATH="/var/lib/slackware"
CACHEDIR="/var/cache/slackware"

# Root check      
if [[ $EUID -ne 0 ]]; then
    printf "Error: This script must be run as root\n"
    exit 1
fi

# Download file with wget ($1=filename; $2=target directory; $3=comment)
fn_download_file() {
    printf ">>> Downloading %s\n" "$3"
    wget -q -nv --no-check-certificate "$1" -P "$2"
}

fn_repo_update() {
    [ -f "$DBPATH/packages.db" ] && rm "$DBPATH/packages.db"
    printf "Synchronizing package databases...\n"
    for i in extra patches; do 
        fn_download_file "$MAIN_MIRROR/$i/PACKAGES.TXT" "$DBPATH" "$MAIN_MIRROR/$i"
        cd $DBPATH || exit
        extract_package_info "$MAIN_MIRROR" "PACKAGES.TXT" >> "$DBPATH/packages.db"; rm PACKAGES.*
    done
    fn_download_file "$MAIN_MIRROR/PACKAGES.TXT" "$DBPATH" "$MAIN_MIRROR"
    extract_package_info "$MAIN_MIRROR" "PACKAGES.TXT" >> "$DBPATH/packages.db"; rm PACKAGES.*
    for ((i=0; i<"${#OTHER_MIRRORS[@]}"; ++i)); do
        fn_download_file "${OTHER_MIRRORS[i]}/PACKAGES.TXT" "$DBPATH" "${OTHER_MIRRORS[i]}"
        if [ -f "$DBPATH/PACKAGES.TXT" ] ; then
            extract_package_info "${OTHER_MIRRORS[i]}" "PACKAGES.TXT" >> "$DBPATH/packages.db"; rm PACKAGES.*
        fi
    done
    printf "Packages: %d\n" "$(grep -c ^ "$DBPATH/packages.db")"
}

extract_package_info() {
awk -v mirror="$1" '
BEGIN {
    FS=": "; OFS="|";
    url = ""; description = "";
}

/^PACKAGE NAME:/ {
    package_name = $2;
    gsub(/^[ \t]+|[ \t]+$/, "", package_name);
}

/^PACKAGE LOCATION:/ {
    gsub(/^[ \t]+|[ \t]+$/, "", $2);
    gsub(/^\./, "", $2);
    url = mirror "/" $2 "/" package_name;
}

/^PACKAGE DESCRIPTION:/ {
    getline;
    description = $0;
    sub(/^.*: /, "", description);
}

/^$/ {
    if (package_name != "" && url != "") {
        print url, description;
    }
    url = ""; description = "";
}

END {
    if (package_name != "" && url != "") {
        print url, description;
    }
}' $2
}

fn_pkg_search_print_out() {
    e_url="$1"
    e_filename="${e_url##*/}"
    e_base="${e_filename%.t?z}"
    e_release="${e_base##*-}"
    e_temp="${e_base%-*}"
    e_arch="${e_temp##*-}"
    e_temp="${e_temp%-*}"
    e_version="${e_temp##*-}"
    e_name="${e_temp%-*}"
    e_desc="$(echo $2 | sed "s/$e_name //g")"
    if [ -d "/var/lib/slackware/installed/$e_name" ]; then
        if [ -f "/var/lib/slackware/installed/$e_name/pkginfo" ]; then
            source "/var/lib/slackware/installed/$e_name/pkginfo"
            if [ "$pkgver" == "$e_version" ] && [ "$pkgrel" == "$e_release" ]; then
                status="[installed]"
            else
                unset status
            fi
        fi
    else
        unset status
    fi
    printf "%-s %-s-%-s %s %s\n" "$e_name" "$e_version" "$e_release" "$e_arch" "$status"
    e_desc_no_braces=$(echo "$e_desc" | sed 's/[()]//g')
    printf "%-s\n\n" "$e_desc_no_braces"
}

fn_pkg_search() {
    if [[ $ARG ]]; then
        PKGSEARCH=$(grep -i "$ARG" "$DBPATH/packages.db")
        if [[ "$PKGSEARCH" != "" ]]; then
            while read -r result; do
                urlR="$(echo "$result" | cut -d '|' -f1)"     # Extract URL
                descriptionR="$(echo "$result" | cut -d '|' -f2)"  # Extract description
                fn_pkg_search_print_out "$urlR" "$descriptionR"
            done <<< "$PKGSEARCH"
        else
            echo "No results found for '$ARG'"
        fi
    else
        echo "Please provide a search term."
    fi
}

fn_get_pkgmatch() {
    grep "/$1-[0-9]" "$DBPATH/packages.db" | head -1 | cut -d '|' -f1
    
}

fn_check_pkgmatch_exists() {
    unset MISSING
    LIST="$@"
    for ONE in $LIST; do  
        PKGMATCH="$(fn_get_pkgmatch $ONE)"
        if [[ $PKGMATCH == "" ]]; then
            MISSING+=("$ONE"); 
        fi
    done
    if [[ ${#MISSING[@]} != 0 ]]; then
        for i in "${MISSING[@]}"; do
            printf "Error: Unable to locate package %s\n" "$i"
        done
        exit 1
    fi
}

fn_pkg_download() {
    if [ $ARG ]; then
        PKGMATCH=$(fn_get_pkgmatch "$ARG")
        if [[ "$PKGMATCH" != "" ]]; then
            FILE=$(basename $PKGMATCH)
            if [ ! -f "$CACHEDIR/$FILE" ]; then
                fn_download_file "$PKGMATCH" "$CACHEDIR" "$FILE"
            fi
            if [ ! -f "$CACHEDIR/$FILE" ]; then
                printf "%s download failed\n" "$(basename "$PKGMATCH")"
                exit 1
            fi
        else
            printf "Error: Unable to locate package %s\n" "$ARG"
        fi
    fi
}

fn_pkg_download_all() {
    fn_check_pkgmatch_exists $ARGD
    max_parallel=7
    current_jobs=0
    for pkg in $ARGD; do
        ARG="$pkg"
        fn_pkg_download &
        current_jobs=$((current_jobs + 1))
        if [ "$current_jobs" -ge "$max_parallel" ]; then
            wait -n
            current_jobs=$((current_jobs - 1))
        fi
    done
    wait
}

fn_write_metadata() {
    nv=$(echo $1 | sed 's/\(.*\)-[^-]*-[^-]*$/\1/')
    pkgname="$(echo $nv | sed 's/-[^-]*$//')"
    pkgver="$(echo $nv | sed 's/.*-//')"
    pkgrel="$(echo ${1##*-} | sed 's/.t.z//')"
    mkdir -p $2/$DBPATH/installed/$pkgname
    echo pkgname="$pkgname" > $2/$DBPATH/installed/$pkgname/pkginfo
    echo pkgver="$pkgver" >> $2/$DBPATH/installed/$pkgname/pkginfo
    echo pkgrel="$pkgrel" >> $2/$DBPATH/installed/$pkgname/pkginfo
    # files
    tar -tvf $1 | awk '!/^d/ {print $NF}' | grep -v "install/" | sed 's/^/\//' > $2/$DBPATH/installed/$pkgname/files
}

fn_pkg_extract() {
    if [[ "$ARG" != "" && -f "$ARG" ]]; then
        printf "Extracting %s\n" "$ARG"
        tar -xf "$ARG"
    else
        printf "Extraction failed: File not found or invalid.\n"
        exit 1
    fi
}

fn_pkg_extract_all() {
    for i in *.t?z; do
        [[ -e "$i" ]] || break
        ARG="$i"
        printf "Installing %s --target-root=./install\n" "$ARG"
        [ ! -d install ] && mkdir install
        tar -xf "$ARG" -C install
        if [ -f "install/install/doinst.sh" ]; then
            cd install && sh ./install/doinst.sh 2>/dev/null
            cd "$OLDPWD" || exit
        fi
        fn_write_metadata "$ARG" install
        if [ -d install/install ]; then
            rm -r install/install
        fi
    done
}

fn_pkg_post_actions() {
    local ICONS
    local DESKTOP
    local GSETTINGS
    local FONTS

    ICONS=$(grep /usr/share/icons/hicolor "$DBPATH/installed/$pkgname/files" || true)
    DESKTOP=$(grep /usr/share/applications "$DBPATH/installed/$pkgname/files" || true)
    GSETTINGS=$(grep /usr/share/glib-2.0/schemas "$DBPATH/installed/$pkgname/files" || true)
    FONTS=$(grep /usr/share/fonts/TTF "$DBPATH/installed/$pkgname/files" || true)

    local file_paths=("$ICONS" "$DESKTOP" "$GSETTINGS" "$FONTS")

    for file_path in "${file_paths[@]}"; do
        if [ "$file_path" ]; then
            case "$file_path" in
                "$ICONS")
                    printf "Updating icon cache...\n"
                    gtk-update-icon-cache /usr/share/icons/hicolor
                    ;;
                "$DESKTOP")
                    printf "Updating desktop database...\n"
                    update-desktop-database
                    ;;
                "$GSETTINGS")
                    printf "Compiling GSettings schemas...\n"
                    glib-compile-schemas /usr/share/glib-2.0/schemas
                    ;;
                "$FONTS")
                    printf "Updating font cache and directories...\n"
                    fc-cache -f -s
                    mkfontscale /usr/share/fonts/TTF
                    mkfontdir /usr/share/fonts/TTF
                    ;;
            esac
        fi
    done
}

fn_run_install_script() {
    if [ -f "$1" ]; then
        cd / && sh "$1" 2>/dev/null
        cd "$OLDPWD"
    fi
}

fn_cleanup_install_directory() {
    if [ -d /install ]; then
        rm -r /install
    fi
}

fn_pkg_install_local() {
    if [[ "$ARG" != "" && -f "$ARG" ]]; then
        printf "Installing %s\n" "$ARG"
        tar -xf "$ARG" -C /
        fn_run_install_script "/install/doinst.sh"
        fn_write_metadata "$ARG" /
        fn_cleanup_install_directory
        fn_pkg_post_actions
    else
        printf "Installation failed: File not found or invalid.\n"
        exit 1
    fi
}

fn_pkg_install() {
    LOCAL="false"
    for ONE in $ARGI; do
        if [ -f "$ONE" ]; then
            LOCAL="true"
            ARG="$ONE"
            NAME=$(echo $ARG | sed 's/\(.*\)-[^-]*-[^-]*$/\1/' | sed 's/-[^-]*$//')
            if [ -d "$DBPATH/installed/$NAME" ]; then
                printf "%s is already installed\n" "$ARG"
            else
                fn_pkg_install_local
            fi
        fi
    done
    if [ "$LOCAL" = true ]; then exit 0; fi
    fn_check_pkgmatch_exists "$ARGI"
    for ONE in $ARGI; do
        ARG="$ONE"
        if [ -d "$DBPATH/installed/$ARG" ]; then
            printf "%s is already installed\n" "$ARG" && exit 1
        fi
    done
    ARGD="$ARGI"
    fn_pkg_download_all
    for ONE in $ARGI; do
        ARG="$ONE"
        PKGMATCH="$(fn_get_pkgmatch "$ARG")"
        FILE=$(basename "$PKGMATCH")
        if [ -f "$CACHEDIR/$FILE" ]; then
            ARG="$FILE"
            cd "$CACHEDIR" && fn_pkg_install_local && cd "$OLDPWD"
        fi
    done
}

fn_pkg_remove() {
    for i in $ARGR; do
        if [ -f "$DBPATH/installed/$i/pkginfo" ]; then
            source "$DBPATH/installed/$i/pkginfo"
            printf "Removing %s\n" "$i"
            cat "$DBPATH/installed/$i/files" | while read -r file; do 
                if [ -f "$file" ]; then 
                    rm "$file"
                fi
            done
            fn_pkg_post_actions
            rm -r "$DBPATH/installed/$i"
        else
            printf "%s is not installed\n" "$i"
        fi
    done
}

fn_pkg_clean_cache() {
    rm $CACHEDIR/* 2>/dev/null
}

fn_pkg_list_installed() {
    local dir
    for dir in "$DBPATH"/installed/*/; do
        [ -f "$dir/pkginfo" ] || continue
        . "$dir/pkginfo"
        printf '%s %s-%s\n' "$pkgname" "$pkgver" "$pkgrel"
    done | sort -k1,1
}

fn_pkg_show_help() {
    printf "Usage: %s <command> [arguments]\n\n" "$(basename "$0")"
    printf "where <command> is one of:\n"
    printf "    %-2s %-42s %s\n" "up:" "Update repository database"
    printf "    %-2s %-42s %s\n" "sr:" "Search for packages"
    printf "    %-2s %-42s %s\n" "dl:" "Download package(s)"
    printf "    %-2s %-42s %s\n" "xp:" "Extract a single package (specify filename)"
    printf "    %-2s %-42s %s\n" "xa:" "Extract all packages from the current directory"
    printf "    %-2s %-42s %s\n" "it:" "Install package(s) (local or from a repository)"
    printf "    %-2s %-42s %s\n" "rm:" "Uninstall package(s)"
    printf "    %-2s %-42s %s\n" "cc:" "Delete cached packages"
    printf "    %-2s %-42s %s\n\n" "li:" "List installed packages"
}

# Arguments
case "$1" in
    up) fn_repo_update ;;
    sr) ARG="$2"; fn_pkg_search ;;
    dl) shift; ARGD="$@"; fn_pkg_download_all ;;
    xp) ARG="$2"; fn_pkg_extract ;;
    xa) fn_pkg_extract_all ;;
    it) shift; ARGI="$@"; fn_pkg_install ;;
    rm) shift; ARGR="$@"; fn_pkg_remove ;;
    cc) fn_pkg_clean_cache ;;
    li) fn_pkg_list_installed ;;
    *) fn_pkg_show_help ;;
esac
