name: CI slackware-packages

on:
  schedule:
    - cron: '0 1 */2 * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo ln -sf /bin/bash /bin/sh

    - name: Create rootfs
      run: |
        sudo sed '$s/fn_compress_rootfs/#fn_compress_rootfs/' -i 2slackware2sb
        sudo sh 2slackware2sb

    - name: Compile packages
      run: |
        sudo mount -t proc proc /tmp/root.x86_64/proc
        sudo mount -t sysfs sys /tmp/root.x86_64/sys
        sudo mount -o bind /dev /tmp/root.x86_64/dev
        sudo cp -a scripts/slackware/repo/create_packages.sh /tmp/root.x86_64/
        sudo cp -a scripts/slackware/repo/SlackBuilds /tmp/root.x86_64/
        sudo cp -a scripts/slackware/repo/gen_repos_files.sh /tmp/root.x86_64/tmp/
        sudo cp -a scripts/slackware/repo/genreprc /tmp/root.x86_64/tmp/
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "sh create_packages.sh"
        sudo umount /tmp/root.x86_64/{proc,sys,dev}

    - name: Create repository data
      run: |
        sudo mkdir /tmp/root.x86_64/tmp/slackware
        sudo cp /tmp/root.x86_64/tmp/*.t?z /tmp/root.x86_64/tmp/slackware
        cd /tmp/root.x86_64/tmp/
        echo $PWD
        ls
        echo | yes | sudo export genreprc && sudo bash ./gen_repos_files.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: slackware-packages
        path: /tmp/root.x86_64/tmp/slackware/*
