name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget tar squashfs-tools

    - name: Compile
      run: sh fedora2sb

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fs-fedora.sb
        path: /mnt/home/data/Downloads/fs-fedora.sb
