name: CI Repo-pkgs

on:
  schedule:
    - cron: '5 1 */2 * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo ln -sf /bin/bash /bin/sh
        sudo apt-get install -y gh jq

    - name: Create rootfs
      run: |
        sudo sed '$s/fn_compress_rootfs/#fn_compress_rootfs/' -i 2slackware2sb
        sudo sh 2slackware2sb

    - name: Compile packages
      run: |
        sudo mount -t proc proc /tmp/root.x86_64/proc
        sudo mount -t sysfs sys /tmp/root.x86_64/sys
        sudo mount -o bind /dev /tmp/root.x86_64/dev
        sudo cp -a scripts/slackware/repo/create_packages.sh /tmp/root.x86_64/
        sudo cp -a scripts/slackware/repo/SlackBuilds /tmp/root.x86_64/
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "sh create_packages.sh"
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "mkdir /tmp/slackware"
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "mv /tmp/*.t?z /tmp/slackware"
        sudo cp -a scripts/slackware/repo/gen_repos_files.sh /tmp/root.x86_64/tmp/
        sudo cp -a scripts/slackware/repo/genreprc /tmp/root.x86_64/tmp/
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "cd /tmp; echo|yes|bash gen_repos_files.sh"
        sudo umount /tmp/root.x86_64/{proc,sys,dev}

    - name: Remove old release assets
      run: |
        release_id=$(gh release list --repo $GITHUB_REPOSITORY --json tag_name --jq '.[] | select(.tag_name == "slackware-current") | .id')
        
        if [ -n "$release_id" ]; then
          gh release delete $release_id --repo $GITHUB_REPOSITORY --yes
        fi

    - name: Create new release and upload assets
      run: |
        gh release create slackware-current --repo $GITHUB_REPOSITORY --notes "New release" /tmp/root.x86_64/tmp/slackware/*
