name: CI Squashfs

on:
  schedule:
    - cron: '5 1 */2 * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo ln -sf /bin/bash /bin/sh

    - name: Create squashfs
      run: sudo sh 2slackware2sb

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release create ${{ github.event.repository.name }}-0.7.0-${{ github.run_number }}
        "/tmp/output/fs-slackware.sb"
