name: Makefile CI slackware-packages

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo ln -sf /bin/bash /bin/sh

    - name: Create squashfs
      run: sudo sh 2slackware2sb

    - name: Compile packages
      run: |
        sudo cp -a slackware/create_packages.sh /tmp/root.x86_64/
        sudo cp -a slackware/SlackBuilds /tmp/root.x86_64/
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "sh create_packages.sh"

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: slackware-packages
        path: /tmp/root.x86_64/tmp/*.t?z
