name: CI SUR

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo ln -sf /bin/bash /bin/sh

    - name: Create rootfs
      run: |
        sudo sed '$s/fn_compress_rootfs/#fn_compress_rootfs/' -i 2slackware2sb
        sudo sh 2slackware2sb

    - name: Compile packages
      run: |
        sudo mount -t proc proc /tmp/root.x86_64/proc
        sudo mount -t sysfs sys /tmp/root.x86_64/sys
        sudo mount -o bind /dev /tmp/root.x86_64/dev
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "fetch \
        it $(fetch sr /d/|grep -v Installed|cut -d '(' -f1)"
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "fetch \
        it qt5"        
        sudo cp -a scripts/slackware/repo/sur.sh /tmp/root.x86_64/
        sudo chroot /tmp/root.x86_64/ /bin/bash -c "sh sur.sh \
        https://slackbuilds.org/slackbuilds/15.0/office/featherpad.tar.gz"
        sudo umount /tmp/root.x86_64/{proc,sys,dev}

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sur
        path: /tmp/root.x86_64/tmp/*.t?z
