name: Makefile CI sb

on:
  schedule:
    - cron: '0 5 * * SUN'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo ln -sf /bin/bash /bin/sh

    - name: Compile
      run: sh 2slik2sb

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fs-slik.sb
        path: /mnt/home/data/Downloads/fs-slik.sb
